### Problem - 1: Array Creation




In [7]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array 2x2:\n", empty_array)


Empty Array 2x2:
 [[2.00193947e-316 0.00000000e+000]
 [6.67180043e-310 6.67180032e-310]]


In [8]:
# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array 4x2:\n", ones_array)




All Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)  # shape (3,3), filled with 7
print("\nFull Array (3x3 filled with 7):\n", full_array)





Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
# 4. Return a new array of zeros with the same shape and type as a given array
array_for_reference = np.array([1, 2, 3, 4])
zeros_like_array = np.zeros_like(array_for_reference)
print("\nZeros Array with shape of array_for_reference:\n", zeros_like_array)




Zeros Array with shape of array_for_reference:
 [0 0 0 0]


In [11]:
# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(array_for_reference)
print("\nOnes Array with shape of array_for_reference:\n", ones_like_array)




Ones Array with shape of array_for_reference:
 [1 1 1 1]


In [12]:
# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("\nNumpy Array from List:\n", numpy_array_from_list)


Numpy Array from List:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [13]:
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("\nArray from 10 to 49:\n", array_range)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix_3x3)


3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_of_array = random_array.mean()
print("\nMean of Random Array:\n", mean_of_array)


Mean of Random Array:
 0.48549942867425977


In [17]:
# 5. Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nMin Value:", min_value, "Max Value:", max_value)


Min Value: 0.0004532754777657466 Max Value: 0.966440360481118


In [18]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)


Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)


Reversed Array:
 [0 4 0 0 2 1]


In [20]:
# 8. Create a 2D array with 1 on border and 0 inside
border_1_array = np.ones((5, 5))
border_1_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:\n", border_1_array)


2D Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checkerboard)


Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


###Problem - 3: Array Operations


In [22]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition_result = x + y
print("\nAddition of x and y:\n", addition_result)


Addition of x and y:
 [[ 6  8]
 [10 13]]


In [23]:
# 2. Subtract the two arrays
subtraction_result = x - y
print("\nSubtraction of x and y:\n", subtraction_result)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [24]:
# 3. Multiply the array with any integer
multiplication_result = x * 2
print("\nMultiplication of x by 2:\n", multiplication_result)


Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]


In [25]:
# 4. Find the square of each element
squared_result = np.square(x)
print("\nSquare of each element in x:\n", squared_result)



Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [26]:
# 5. Find the dot product between:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot Product v and w:", dot_v_w)
print("Dot Product x and v:\n", dot_x_v)
print("Dot Product x and y:\n", dot_x_y)


Dot Product v and w: 219
Dot Product x and v:
 [29 77]
Dot Product x and y:
 [[19 22]
 [50 58]]


In [27]:
# 6. Concatenate x and y along row and concatenate v and w along column
concat_xy_row = np.concatenate((x, y), axis=1)
concat_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenate x and y along row:\n", concat_xy_row)
print("\nConcatenate v and w along column:\n", concat_vw_column)


Concatenate x and y along row:
 [[1 2 5 6]
 [3 5 7 8]]

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [28]:
# 7. Concatenate x and v
# This will raise an error because x is 2D and v is 1D with incompatible shapes
try:
    concat_x_v = np.concatenate((x, v), axis=1)
except Exception as e:
    print("\nError during concatenating x and v:", e)


Error during concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### Problem - 4: Matrix Operations

In [29]:
# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("\nA * A^-1 = I:\n", identity_matrix)


A * A^-1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [30]:
# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB == BA:", np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB == BA: False


In [31]:
# 3. Prove (AB)^T = B^T * A^T
transpose_AB = np.transpose(np.dot(A, B))
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", transpose_AB)
print("\nB^T * A^T:\n", transpose_BA)
print("\n(AB)^T == B^T * A^T:", np.array_equal(transpose_AB, transpose_BA))


(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

(AB)^T == B^T * A^T: True


In [32]:
# Solving the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
# Solve for x, y, z
solution = np.linalg.solve(coefficients, constants)
print("\nSolution of the system of equations (x, y, z):\n", solution)



Solution of the system of equations (x, y, z):
 [ 2.  1. -2.]


###Problem 5: Speed Comparison (NumPy vs Python Lists)

In [33]:
import time

# 1. Element-wise Addition
size = 1000000
list_a = list(range(size))
list_b = list(range(size))

In [34]:
# Using Python Lists
start = time.time()
list_sum = [list_a[i] + list_b[i] for i in range(size)]
end = time.time()
print("\nTime for element-wise addition using Python lists:", end - start)


Time for element-wise addition using Python lists: 0.10127902030944824


In [35]:
# Using NumPy Arrays
a = np.arange(size)
b = np.arange(size)

start = time.time()
numpy_sum = a + b
end = time.time()
print("Time for element-wise addition using NumPy arrays:", end - start)

Time for element-wise addition using NumPy arrays: 0.01853799819946289


In [36]:
# 2. Element-wise Multiplication
# Using Python Lists
start = time.time()
list_multiply = [list_a[i] * list_b[i] for i in range(size)]
end = time.time()
print("\nTime for element-wise multiplication using Python lists:", end - start)


Time for element-wise multiplication using Python lists: 0.19034075736999512


In [37]:
# Using NumPy Arrays
start = time.time()
numpy_multiply = a * b
end = time.time()
print("Time for element-wise multiplication using NumPy arrays:", end - start)


Time for element-wise multiplication using NumPy arrays: 0.016328811645507812


In [38]:
# 3. Dot Product
# Using Python Lists
start = time.time()
dot_product_python = sum([list_a[i] * list_b[i] for i in range(size)])
end = time.time()
print("\nTime for dot product using Python lists:", end - start)


Time for dot product using Python lists: 0.2729649543762207


In [39]:
# Using NumPy Arrays
start = time.time()
dot_product_numpy = np.dot(a, b)
end = time.time()
print("Time for dot product using NumPy arrays:", end - start)

Time for dot product using NumPy arrays: 0.0022554397583007812


In [43]:
# 4. Matrix Multiplication
matrix_size = 1000
matrix_a = np.random.random((matrix_size, matrix_size))
matrix_b = np.random.random((matrix_size, matrix_size))


In [42]:
# Using Python Lists (This will be slow and inefficient)
start = time.time()
matrix_multiply_python = [[sum(matrix_a[i][k] * matrix_b[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("\nTime for matrix multiplication using Python lists:", end - start)



Time for matrix multiplication using Python lists: 801.1389710903168


In [44]:
# Using NumPy Arrays
start = time.time()
matrix_multiply_numpy = np.dot(matrix_a, matrix_b)
end = time.time()
print("Time for matrix multiplication using NumPy arrays:", end - start)

Time for matrix multiplication using NumPy arrays: 0.0011682510375976562
